# Generated by Django 4.1.7 on 2023-03-17 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_account', '0002_alter_account_account_ballance_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
