# Generated by Django 4.1.7 on 2023-03-17 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_account', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_ballance',
            new_name='account_balance',
        ),
    ]
