# Generated by Django 4.1.7 on 2023-03-23 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main_account.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_account', '0005_rename_account_ballance_account_account_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tranction', models.CharField(max_length=100)),
                ('invest_from', models.CharField(default='Wallet Address', max_length=100)),
                ('plan', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('refrence_id', models.CharField(default=main_account.models.refrence_id, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
