# Generated by Django 4.1.7 on 2023-03-29 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_account', '0008_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
