# Generated by Django 4.1.7 on 2023-03-17 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
